{"name": "test_login_sucess2", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <learnAllure.TestLogin object at 0x0000023CA3D1E6C8>\n\n    @allure.story(\"登录成功\")\n    def test_login_sucess2(self):\n>       assert \"1\" == 1\nE       AssertionError: assert '1' == 1\n\nlearnAllure.py:38: AssertionError"}, "start": 1695299240733, "stop": 1695299240733, "uuid": "4a98f19a-32e3-4087-adae-195f25eff8b3", "historyId": "686752c7d39d4730a6006528a49e9311", "testCaseId": "686752c7d39d4730a6006528a49e9311", "fullName": "learnAllure.TestLogin#test_login_sucess2", "labels": [{"name": "story", "value": "登录成功"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "learnAllure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-DIJQUJHB"}, {"name": "thread", "value": "12308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "learnAllure"}]}