{"name": "test_login_sucess2", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <learnAllure.TestLogin object at 0x000002159F907F88>\n\n    @allure.story(\"登录成功\")\n    def test_login_sucess2(self):\n>       assert \"1\" == 1\nE       AssertionError: assert '1' == 1\n\nlearnAllure.py:38: AssertionError"}, "start": 1711622564114, "stop": 1711622564114, "uuid": "5c513392-bb84-4816-b0fe-afb5a0de77c2", "historyId": "686752c7d39d4730a6006528a49e9311", "testCaseId": "686752c7d39d4730a6006528a49e9311", "fullName": "learnAllure.TestLogin#test_login_sucess2", "labels": [{"name": "story", "value": "登录成功"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "learnAllure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-DIJQUJHB"}, {"name": "thread", "value": "2968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "learnAllure"}]}